name: Docker Image CI

on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: node-red

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout node-red-docker for custum build
      run: |
        pwd
        ls -la
        git clone https://github.com/node-red/node-red-docker.git
        pwd
        ls -la
    - name: Change dir to docker-custom
      run: cd node-red-docker/docker-custom
    - name: Change Node.js to version 14
      run: |
        pwd
        ls -la
        sed -i 's/NODE_VERSION=[0-9]*/NODE_VERSION=14/' docker-alpine.sh
    - name: Run build
      run: ./docker-alpine.sh
      
    - uses: actions/checkout@v2
    - name: Build the Docker image with dependencies enabled
      run: docker build . --file Dockerfile --tag kvalitetsit/node-red:$(date +%s)
    
    - name: Log into registry
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      
    - name: Push image
      run: docker push kvalitetsit/node-red:$(date +%s)

